### ISSUE TITLE
Support to MassTransit latest version?

### ISSUE THREAD

**Issue by serpargu** [appccelerate/distributedeventbroker.masstransit#1]
Hi, I was wondering whether you have on mind to update the project and make it compatible with MassTransit latest version?

**Comment by philippdolder** [comment]
we don't plan to further invest in maintaining distributed event broker. If you like to provide a pull request we're happy to integrate it

**Comment by MasallahOZEN** [comment]
Hi, why you don't plan that? How make Process distributed flow ?

**Comment by philippdolder** [comment]
if you have the need for a distributed event / messaging platform we advise you to look into purpose built solutions
